### ISSUE TITLE
Delete Entities and relations handling

### ISSUE THREAD

**Issue by Schavras** [indera-solutions/nima#71]
Product

- [x] Remove variations
- [x] Remove Connected Attributes
- [x] Remove From collection
- [x] Remove From sales
- [x] Remove From Vouchers
- [x] Remove from checkout lines with deleting the whole line
- [x] Remove from order only by removing key

Attribute
- [x] Remove From Product Attribute
- [x] Remove From Products relations
- [x] Remove all values

Attribute Value
- [x] Remove from product

Categories
- [x] Remove from sales
- [x] Remove from vouchers
- [x] ~~Move products to another collection (delete should fail if there are products and the target category is not provided~~ We will just throw error if there are products in category

Collections:
- [x] Remove all connections from products

Vouchers:
- [x] Remove all connections from products, collections and categories
- [x] Remove from checkouts

Sales:
- [x] Remove all connections from products, collections and categories
- [x] Remove from checkouts

Shipping Methods:
- [x] Soft delete method
- [ ] ~~Remove all zones~~
- [ ] ~~**Decide what to do with the orders**~~

Shipping Zone
- [ ] ~~**Decide what to do with the orders**~~

@JohnBelly95 missing anything else we should handle?

**Comment by JohnBelly95** [comment]
I think that with Shipping Zones, Shipping Methods and Products we should act on each affected order depending on its status. 

If an order has been shipped, there should be no problem removing the resources.

If an order has not been shipped yet, The admin/staff-member that is attempting to delete the resource should be notified about the affected orders and asked to verify the delete action, or made to update the orders so that they are no longer affected, either by changing the product/shipping information, or canceling it all-together, accoring to the customer's wishes.

In every case, I think the best course of action would be to archive the deleted resource and keep it inaccesible to regular users. That way order data will not be be affected.
